project:
  type: website

website:
  title: "Tranquillyzer Documentation"
  description: "Documentation site for Tranquillyzer, a deep-learning framework for processing long-read scRNA-seq data"
  page-footer:
    left: "Copyright 2025, The Shen Lab at Van Andel Institute"
    right:
      - icon: github
        href: https://github.com/huishenlab/tranquillyzer
  navbar:
    search: true
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: webpages/install.qmd
        text: Install
      - href: webpages/quick_start.qmd
        text: Quick Start
      - href: webpages/pipeline_guide.qmd
        text: Pipeline Guide
      - href: webpages/model_training.qmd
        text: Model Training
      - href: webpages/resource_requirements.qmd
        text: Resource Requirements
      - href: webpages/usage.qmd
        text: CLI Reference
      - href: webpages/releases.qmd
        text: Releases
      - href: webpages/contributing.qmd
        text: Contributing
    right:
      - icon: github
        href: https://github.com/huishenlab/tranquillyzer
  sidebar:
    - title: "Pipeline Guide"
      style: "docked"
      contents:
        - text: "Overview"
          href: webpages/pipeline_guide.qmd
        - text: "Preprocessing"
          href: webpages/pipeline/preprocessing.qmd
        - text: "Annotation"
          href: webpages/pipeline/annotation.qmd
        - text: "Barcode Correction & Demux"
          href: webpages/pipeline/barcode_demux.qmd
        - text: "Alignment & Deduplication"
          href: webpages/pipeline/align_dedup.qmd
        - text: "BAM Splitting"
          href: webpages/pipeline/split_bam.qmd
        - text: "QC Metrics"
          href: webpages/pipeline/qc_metrics.qmd
        - text: "Visualization"
          href: webpages/pipeline/visualization.qmd
    - title: "Model Training"
      style: "docked"
      contents:
        - text: "Overview"
          href: webpages/model_training.qmd
        - text: "Read Simulation"
          href: webpages/model_training/read_simulation.qmd
        - text: "simulate-data CLI"
          href: webpages/model_training/simulate_data_cli.qmd
        - text: "Model Training"
          href: webpages/model_training/train_model.qmd
        - text: "train-model CLI"
          href: webpages/model_training/train_model_cli.qmd
        - text: "Model Assessment"
          href: webpages/model_training/assess_model.qmd

format:
  html:
    theme: lumen
    highlight-style: solarized
    css: styles.css
    toc: true
    code-copy: true
    code-block-border-left: "#000000"
    code-block-bg: "#F3F3F3"
