name: Run Pytest

on:
  push:
    branches: [main, dev, annot_demux_refactor]
  pull_request:
    branches: [main, dev, annot_demux_refactor]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: tranquillyzer
          environment-file: environment.yml
          auto-activate-base: false
          miniforge-variant: Mambaforge
          miniforge-version: 22.9.0-2
          use-mamba: true
          python-version: "3.10.12"

      - name: Install Python packages (extra)
        shell: bash -l {0}
        run: |
          pip install -e .
          pip install pytest pytest-order pytest-cov

      - name: Download model and reference
        shell: bash -l {0}
        run: |
         mkdir -p tests/10x3p/data tests/references
         curl -L "https://www.dropbox.com/scl/fi/re7f2s36jr3mijdwpvvc7/10x3p_sc_ont_011_w_CRF.h5?rlkey=7pcxny332fuctr3aw1xew5j8z&dl=1" -o models/10x3p_sc_ont_013.h5
         curl -L "https://www.dropbox.com/scl/fi/umoonedt500khhhvebu7r/10x3p_sc_ont_011_w_CRF_params.json?rlkey=28xl4toxtzzff60954dhv1m4t&dl=1" -o models/10x3p_sc_ont_013_params.json
         curl -L "https://www.dropbox.com/scl/fi/313vfpp5usgknfi9o375n/10x3p_sc_ont_011_w_CRF_lbl_bin.pkl?rlkey=ofc6drcra7rs1js0t71psavu0&dl=1" -o models/10x3p_sc_ont_013_lbl_bin.pkl
         curl -L "https://www.dropbox.com/scl/fi/9203pc2gz45u419kze446/hg38_gencode_chr21.fa?rlkey=k1co80pso7zsvb8oiqqc1o1dy&st=e0e92h5h&dl=1" -o tests/references/hg38_gencode_chr21.fa
         curl -L "https://www.dropbox.com/scl/fi/9zvh26moro7frfho818ko/hg38_gencode_chr21.gtf?rlkey=v3s05m9ap3srpjhvl5yfjfeq7&st=hn6mufoq&dl=0" -o tests/references/hg38_gencode_chr21.gtf

      - name: Run Pytest with coverage
        shell: bash -l {0}
        run: |
          pytest --maxfail=1 -q \
                 --cov=. \
                 --cov-report=term-missing \
                 --cov-report=xml:coverage.xml

      - name: Combine coverage (explicit)
        shell: bash -l {0}
        run: |
          python - <<'PY'
          import coverage
          cov = coverage.Coverage(data_file=".coverage")
          cov.load()
          cov.combine()
          cov.xml_report(outfile="coverage.xml")
          PY

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
